# Default values for secure-qna app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
modelVolume: model-repository
modelRepoName: model-store

frontend:
  replicaCount: 1
  name: chatbot-app
  image:
    repository: dpoulopoulos/chatbot-app
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: v1.4.0-78cda62

sqlCoder:
  name: sql-llm
  port: 8000
  replicaCount: 1
  containerPort: 8000
  hostPort: 8000
  image:
    repository: vllm/vllm-openai
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: v0.4.3
  resources:
    limits:
      nvidia.com/gpu: 2
    requests:
      nvidia.com/gpu: 2

llm:
  name: llama2-7b-chat-1xgpu-day0
  modelName: Llama-2-7b-chat-hf
  nimModelName: llama2-7b-chat
  minReplicaCount: 1
  modelFormat: "nvidia-nim-llm"
  runtime: nvidia-nim-llm-24.02.day0
  numGPUs: 1
  resources:
    limits:
      cpu: "8"
      memory: 64Gi
      nvidia.com/gpu: 1
    requests:
      cpu: "6"
      memory: 48Gi
      nvidia.com/gpu: 1

embeddings:
  name: nv-embed-qa
  modelVersion: 4
  nimModelName: nv-embed-qa
  modelFormat: nvidia-nim-embedding
  runtime: nvidia-nim-embedding-24.02
  minReplicaCount: 1
  resources:
    limits:
      cpu: 8
      memory: 128Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 6
      memory: 64Gi
      nvidia.com/gpu: 1

agent:
  langserveHost: 0.0.0.0
  langservePort: 9000
  pullPolicy: Always
  replicaCount: 1
  containerName: chain-server
  image:
    repository: dpoulopoulos/chatbot-agent
    tag: v1.4.0-a02659a

imagePullSecrets:
  - name: ngc-secret

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podSecurityContext: {}
# fsGroup: 2000

securityContext:
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
  runAsUser: 0

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

#Platform related options
ezua:
  domainName: "${DOMAIN_NAME}"
  #Use next options in order to configure the application endpoint.
  #Example of a VirtualService is here:
  virtualService:
    endpoint: "hpe-portfolio-assistant.${DOMAIN_NAME}"
    istioGateway: "istio-system/ezaf-gateway"

  authorizationPolicy:
    namespace: "istio-system"
    providerName: "oauth2-proxy"
    matchLabels:
      istio: "ingressgateway"

ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
