
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-simplification-deployment
  labels:
    app: {{ .Values.app }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
      - name: text-simplification
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}